---
- name: Install Git, Ruby && Bundler
  hosts: all
  become: true
  tasks:
    # Установим в цикле все зависимости
    - name: Install ruby and rubygems and required packages
      apt: "name={{ item }} state=present"
      with_items:
        - git
        - ruby-full
        - ruby-bundler
        - build-essential
